//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Hazelcast .Net Client")]
[assembly: System.Reflection.AssemblyDescription("Hazelcast .Net Client ")]
[assembly: System.Reflection.AssemblyCompany("Hazelcast Inc.")]
[assembly: System.Reflection.AssemblyProduct("Hazelcast Enterprise Edition")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) 2008-2015, Hazelcast, Inc")]
[assembly: System.Reflection.AssemblyConfiguration("Commit 027d241")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyVersion("3.7.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("3.7.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("3.7.0.0")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo(@"Hazelcast.Test, PublicKey=0024000004800000940000000602000000240000525341310004000001000100bd5d5688b7bd9da342a5ee8757a674cccf445ea3411a40dd387bb18eb8e2588aedfc8779aac7bc09cd99189d52888d587b892a9b9bad875aabd58f3f91945436bd6a95910f3663b0c551a90a4fb3328419ceada81f9dd09ed45b011371ebe8a8f5d6d6bc342e396f126e31257e341a3c18f17c11ab183ab62b5ae6c86c2e2696")]


